# Generated by Django 5.1.3 on 2024-11-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiration_date",
            field=models.DateField(),
        ),
    ]
