# Generated by Django 5.1.3 on 2024-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produto", "verbose_name_plural": "Produtos"},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="product",
            name="expiration_date",
            field=models.DateField(verbose_name="Data de Validade"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Preço"
            ),
        ),
    ]
