# Generated by Django 5.1.3 on 2024-11-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Aluno", "verbose_name_plural": "Alunos"},
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="student",
            name="lastname",
            field=models.CharField(max_length=100, verbose_name="Sobrenome"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
